name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Build and Publish
      run: |
        dotnet publish -c Release -o ./publish
        mkdir -p dist
        mv ./publish/* dist/
        
    - name: Criar arquivo ZIP
      run: zip -r dist/fast-food.lambda.auth.zip dist/*    
      
    - name: Listar conteúdo do diretório de publicação
      run: ls ./dist
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Deploy to AWS Lambda
      run: |
         aws lambda create-function \
          --function-name fast-food-lambda-auth \
          --runtime dotnetcore8.0 \
          --role  ${{ vars.AWS_ROLE_ARN }} \
          --handler fast-food.lambda.auth::fast_food.lambda.auth.Function::FunctionHandler \
          --zip-file fileb://./dist/fast-food.lambda.auth.zip
